/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BalancedTrees;

import org.junit.Before;
import org.junit.Test;

import java.io.*;
import java.util.Random;

import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.*;

public class LLRBTTest {
    private int numNodes;
    private OrderedMap<String, Integer> st;

    private ByteArrayOutputStream os;
    private PrintStream ps;

    private TinyST<BST<String, Integer>> test;



    @Before
    @SuppressWarnings("unchecked")
    public void initialize() {
        st = new LLRBTree<>();
        TinyST.buildTinyST(st);
        os = new ByteArrayOutputStream();
        ps = new PrintStream(os);
        numNodes = 1000;
        test = new TinyST(LLRBTree.class);
    }
    @Test
    public void testInsert1() {

        ps.println("size = " + st.size());
        ps.println("min  = " + st.min());
        ps.println("max  = " + st.max());

        String add =
                "size = 10\n" +
                        "min  = A\n" +
                        "max  = X\n";
        assertThat(os.toString(), equalTo(add));
    }

    @Test
    public void testKeys() {
        test.testKeys();
    }
    @Test
    public void testSelect() {
        test.testSelect();
    }
    @Test
    public void testFloorCeil() {
        test.testFloorCeil();
    }
    @Test
    public void testRangeSearch() {
        test.testRangeSearch();
    }

    @Test
    public void testDelete1() {
        test.testDelete();
    }

    @Test public void testInsert2() {
        LLRBTree<Integer, Integer> st2 = new LLRBTree<>();
        for (int i = 0; i < numNodes; i++) {
            st2.put(i, i);
            assertThat(st2.check(), is("pass"));
        }
        assertThat(st2.height(), is(9));
    }

    @Test public void testDelete2() {
        // delete keys in random order
        LLRBTree<Integer, Integer> st2 = new LLRBTree<>();

        for (int i = 0; i < numNodes; i++) {
            st2.put(i, i);
        }

        final int seedNum = 0;
        Random gen = new Random(seedNum);
        while (st2.size() > 0) {
            int i = gen.nextInt(numNodes);
            if (st2.contains(i)) {
                st2.delete(i);
                assertThat(st2.check(), is("pass"));
            }
        }
        assertThat(st2.isEmpty(), is(true));
    }

}
